import { i18n } from '@/i18n-config';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import LocaleSwitcher from '../../components/locale-switcher';
import '../globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: string };
}) {
  return (
    <html lang={params.lang}>
      <body className={inter.className}>
        <LocaleSwitcher />
        <br />
        <p>Current locale: {params.lang}</p>
        <br />
        <br />
        <br />
        {children}
      </body>
    </html>
  );
}
